== Git basics

This section covers:

- git init
- the .git folder
- git log
- git status
- git add
- git commit
- git diff

This section is important because these are the basic tools you will most often
use with git.

To initialise a git repository, run 'git init' from within the root folder
of the source you want to manage.

----
$ rm -rf 1.2.1
$ mkdir 1.2.1
$ cd 1.2.1
$ git init
----

This initialises a database in the folder '.git' locally.
Your repository is entirely stored within this .git folder. There are no
other files elsewhere on your filesystem you need to be concerned about.
(There are config files for git, but these are global to the host. We can ignore
them for now.)

----
$ cd .git
$ ls
config
description
HEAD
hooks
info
objects
refs
$ cd ..
----

It's not part of the scope of this course to go into detail about the git
internals files seen here.

What is worth being aware of here are:

- the 'HEAD' file
- config

=== HEAD

The HEAD is key - it points to the current branch you are 'on'.

If we look at the file, we see it points to the refs/heads/master.

This is an internal representation of the default 'master' branch.

----
$ cat HEAD
ref: refs/heads/master
----

=== config

'config' stores information about your repository's local configuration, eg
what branches and remote repositories your repository is aware of. It's a plain
text file:

----
$ cat config
[core]
	repositoryformatversion = 0
	filemode = true
	bare = false
	logallrefupdates = true
	ignorecase = true
	precomposeunicode = true
----

=== git log

If we want to look at the history of this repository, you can run the git log
command:

----
$ cd ..
$ git log
fatal: bad default revision 'HEAD'
----

We have a problem! This repository has no history to look at.

Git has followed the 'HEAD' pointer to the refs/heads/master entry and found
nothing there! And indeed there is nothing there:

----
$ ls .git/refs/heads/master
ls: .git/refs/heads/master: No such file or directory
----

You need to create a history.

=== git status

As is often the case, git status is your friend:

----
$ git status
On branch master

Initial commit

nothing to commit (create/copy files and use "git add" to track)
----

It tells you where the HEAD is pointed at (the non-existent master branch), and
that there is 'nothing to commit'.

Create a file and check status again:

----
$ touch mycode.py
$ git status
On branch master

Initial commit

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	mycode.c
----

We are now advised that we have an 'untracked' file. Git has detected that it
exists but the repository is not 'aware' of it.

Make git aware of it by adding it to the repository.

=== git add

----
$ git add mycode.py
$ git status
On branch master

Initial commit

Changes to be committed:
  (use "git rm --cached <file>..." to unstage)

	new file:   mycode.py
----

We have added a file to the index ready to be committed to the repository.

Remember the four stages we talked about before:

1) Local changes (working directory)
2) Staging/Adding/Index
3) Committing to local Repo
4) Pushing to remote

We create our file (1- local changes), then added/staged it to the index (2)
and then committed to the local repository.

Still we have no history!

----
$ git log
fatal: bad default revision 'HEAD'
----

So we need to commit it to the repository to get a history.

=== git commit

----
$ git commit
$ git log
commit e5fb099e952e8754b54f9b99be93d62e3fce0fca
Author: ianmiell <ian.miell@gmail.com>
Date:   Tue Apr 26 07:46:58 2016 +0100

    Some message
----

Now that git is aware of this file you can make a change to it and show
how the local change looks using git diff.

=== git diff

----
$ vi mycode.py
$ git diff
----

Again, you can see what's going on by looking at the status. You can commit
changes to files and add at the same time by doing 'commit -a'

----
$ git status
$ git commit -a
$ git status
----

git log now shows the history of the file:

----
$ git log
----


=== What you learned

- git init
- the .git folder
- HEAD - a pointer to where in the history we are
- git log
- git status
- git add
- git commit
- git diff


=== Exercises

1) Create a git repo

2) Add and commit a file to the repo

3) Commit a few more changes, and then run git log to view the history
