Cloning a repo
--------------

- git clone
- git reset

In this section we're going to play with the contents of our repository by
deleting the content and seeing what our options are to recover from the
repository.

----
git clone https://github.com/ianmiell/shutit
cd shutit
ls .git
----

There's .git, just as before.

Recall the 4 stages of data in a git repo:

1) Local changes (working directory)
2) Staging/Adding/Index
3) Committing to local Repo
4) Pushing to remote

----
git log                           # default history of this repo
git log --oneline                 # more concise history of this repo
git log --oneline --graph         # graphical view of the history of this repo
cd ..                             # exit this repo's root folder
git clone shutit cloned_shutit    # clone the repository
cd cloned_shutit                  # enter the repository
ls .git                           # we have a copy of the repository's history
rm -rf *                          # delete all the files!
ls .git                           # The .git folder is still there
----

We have cloned the repository, and 'accidentally' deleting

----
git status        # reports that we have deleted files in working tree/directory
git add .         # added to staging/index area
git status        # reports that . Note there's a helpful message about resetting now! Let's explore that.
git reset --mixed # the default. out of staging/index area, but still deleted in the working directory!
git status        # we are back to 'deleted in the working directory' with a message about being ready to add
rm -rf *          # delete all the files again
git add .         # added to staging/index area ready to commit again
git reset --hard  # does a re-check out of the whole repository, discarding working directory and changes to the index
git status        # we now have a consistent state between 1 (local changes) and 3 (committed)
----


What we learned
---------------

- git clone
- git reset

