MAKEFILE_DIR:=$(dir $(CURDIR)/$(word $(words $(MAKEFILE_LIST)),$(MAKEFILE_LIST)))
MAKEFILE_BASENAME:=$(shell basename $(MAKEFILE_DIR))

include ../makefiles/Makefile.constants

CHAPTER_SOURCE:=$(shell ls $(MAKEFILE_DIR)/*.asciidoc)
CHAPTER_TARGET:=$(OUTPUT_DIR)/$(MAKEFILE_BASENAME).html

all: diagrams 

.PHONY: diagrams
diagrams:
	$(MAKE) -C diagrams

