MAKEFILE_DIR:=$(dir $(CURDIR)/$(word $(words $(MAKEFILE_LIST)),$(MAKEFILE_LIST)))
MAKEFILE_BASENAME:=$(shell basename $(MAKEFILE_DIR))

include ../makefiles/Makefile.constants

CHAPTER_SOURCE=$(MAKEFILE_DIR)/$(MAKEFILE_BASENAME).asciidoc
CHAPTER_TARGET=$(OUTPUT_DIR)/$(MAKEFILE_BASENAME).html

all: diagrams $(CHAPTER_TARGET)	

.PHONY: diagrams
diagrams:
	$(MAKE) -C diagrams

$(CHAPTER_TARGET): $(CHAPTER_SOURCE)
	asciidoctor -n -D $(OUTPUT_DIR) $(CHAPTER_SOURCE)


