include ../../makefiles/Makefile.constants
MERMAID_FILES:=$(wildcard *.mermaid)
OBJ_FILES:=$(patsubst %.mermaid,$(OUTPUT_DIR)/%.mermaid.png,$(MERMAID_FILES))


$(OUTPUT_DIR)/%.mermaid.png: %.mermaid
	mermaid -o $(OUTPUT_DIR) $<

all: $(OBJ_FILES)

